# Generated by Django 4.2.4 on 2023-09-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="be",
            name="statuts",
            field=models.CharField(
                choices=[
                    ("E", "Entry"),
                    ("B", "Billed"),
                    ("I", "In progress"),
                    ("C", "Completed"),
                    ("O", "Out"),
                ],
                default="E",
                max_length=1,
            ),
        ),
    ]
