# Generated by Django 4.2.4 on 2023-09-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0002_be_statuts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="be",
            old_name="statuts",
            new_name="status",
        ),
    ]
