# Generated by Django 4.2.4 on 2023-09-27 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0003_rename_statuts_be_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="be",
            name="date_entry",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="be",
            name="time_entry",
            field=models.TimeField(default=datetime.time(5, 49, 15, 139134)),
        ),
        migrations.CreateModel(
            name="BE_ligne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField(default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TPN", "TPN"),
                            ("TPG", "TPG"),
                            ("TPI", "TPI"),
                            ("TPP", "TPP"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "be",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="entry.be"
                    ),
                ),
            ],
        ),
    ]
