# Generated by Django 4.1.7 on 2023-09-28 04:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_delete_be'),
        ('entry', '0004_alter_be_date_entry_alter_be_time_entry_be_ligne'),
    ]

    operations = [
        migrations.CreateModel(
            name='BE_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('TPN', 'TPN'), ('TPG', 'TPG'), ('TPI', 'TPI'), ('TPP', 'TPP')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='be',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
        migrations.AlterField(
            model_name='be',
            name='time_entry',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='BE_ligne',
        ),
        migrations.AddField(
            model_name='be_line',
            name='be',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.be'),
        ),
    ]
