# Generated by Django 4.1.7 on 2023-10-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_alter_be_line_be'),
    ]

    operations = [
        migrations.AddField(
            model_name='be_line',
            name='length',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='be_line',
            name='width',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='be_line',
            name='type',
            field=models.CharField(choices=[('TPN', 'TPN'), ('TPG', 'TPG'), ('TPI', 'TPI'), ('TPP', 'TPP')], default='TPN', max_length=3),
        ),
    ]
