# Generated by Django 4.1.7 on 2023-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_be_line_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='be_line',
            name='thickness',
            field=models.CharField(choices=[('30/100', '30/100'), ('40/100', '40/100'), ('50/100', '50/100'), ('60/100', '60/100'), ('7/10', '7/10'), ('8/10', '8/10'), ('9/10', '9/10'), ('10/10', '10/10'), ('11/10', '11/10'), ('12/10', '12/10'), ('15/10', '15/10'), ('2 mm', '2 mm'), ('3 mm', '3 mm'), ('4 mm', '4 mm')], default='8/10', max_length=6),
        ),
        migrations.AlterField(
            model_name='be_line',
            name='owner',
            field=models.CharField(choices=[('Client', 'Client'), ('Hanitra', 'Hanitra'), ('Tojo', 'Tojo'), ('Plitech', 'Plitech')], default='Client', max_length=10),
        ),
    ]
