# Generated by Django 4.1.7 on 2023-10-07 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_be_line_thickness_alter_be_line_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('item', models.CharField(max_length=20)),
                ('up', models.IntegerField()),
                ('fini', models.IntegerField()),
                ('dvlp', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('be', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entry.be')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='entry.invoiceline')),
            ],
        ),
    ]
