# Generated by Django 4.1.7 on 2023-10-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_rename_up_invoiceline_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='line',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.invoice'),
            preserve_default=False,
        ),
    ]
