# Generated by Django 4.2.4 on 2023-10-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0012_remove_invoice_line_invoiceline_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceline",
            name="invoice",
        ),
    ]
