# Generated by Django 4.2.4 on 2023-10-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0013_remove_invoiceline_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="be",
        ),
    ]
