# Generated by Django 4.2.4 on 2023-10-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0014_remove_invoice_be"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="be",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="entry.be"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="invoice",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_name",
                to="entry.invoice",
            ),
            preserve_default=False,
        ),
    ]
