# Generated by Django 4.1 on 2023-10-10 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customers_company_alter_customers_contact_and_more'),
        ('entry', '0017_alter_invoice_be'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remise',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_sm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='be',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bes', to='customers.customers'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='be',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entry.be'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='entry.invoice'),
        ),
    ]
