# Generated by Django 4.1 on 2023-10-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_invoice_remise_invoice_total_invoice_total_sm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='remise',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='discount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(verbose_name='Total machine fees'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_sm',
            field=models.IntegerField(verbose_name='Total metal price'),
        ),
    ]
