# Generated by Django 4.1.7 on 2023-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_remove_invoice_remise_invoice_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banknote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_20_000', models.IntegerField()),
                ('b_10_000', models.IntegerField()),
                ('b_5_000', models.IntegerField()),
                ('b_2_000', models.IntegerField()),
                ('b_1_000', models.IntegerField()),
                ('b_500', models.IntegerField()),
                ('b_200', models.IntegerField()),
                ('b_100', models.IntegerField()),
            ],
        ),
    ]
