# Generated by Django 4.1.7 on 2023-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0021_banknote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banknote',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
