# Generated by Django 4.1.7 on 2023-10-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0023_alter_banknote_b_100_alter_banknote_b_10_000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banknote',
            name='b_100',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='b_10_000',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='b_1_000',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='b_200',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='b_20_000',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='b_2_000',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='b_500',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='b_5_000',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
