# Generated by Django 4.1.7 on 2023-10-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0024_alter_banknote_b_100_alter_banknote_b_10_000_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='be_line',
            name='eq_sm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total machine fees'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_sm',
            field=models.IntegerField(default=0, verbose_name='Total metal price'),
        ),
    ]
