# Generated by Django 4.1 on 2023-10-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_rename_eq_sm_be_line_sm_eqv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='be_line',
            name='sm_eqv',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
