# Generated by Django 4.2.4 on 2023-10-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0028_invoiceline_be_line_alter_invoiceline_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="metal_scrap",
            field=models.DecimalField(
                decimal_places=5, default=0, max_digits=5, verbose_name="Metal SCRAP"
            ),
            preserve_default=False,
        ),
    ]
