# Generated by Django 4.1 on 2023-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0030_alter_invoice_metal_scrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='metal_scrap',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Metal SCRAP'),
        ),
    ]
