# Generated by Django 4.2.4 on 2023-10-24 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0034_be_line_created_at_be_line_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="be",
            name="date_entry",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Entry Date"
            ),
        ),
        migrations.AlterField(
            model_name="be",
            name="time_entry",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Entry Time"
            ),
        ),
    ]
