# Generated by Django 5.1.1 on 2025-01-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0035_alter_be_date_entry_alter_be_time_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advance',
            field=models.IntegerField(default=0, verbose_name='initial payment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balanced_due',
            field=models.IntegerField(default=0, verbose_name='Balance Due'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.IntegerField(default=0, verbose_name='Grand total'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
