# Generated by Django 5.1.1 on 2025-01-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0036_invoice_advance_invoice_balanced_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_status',
            field=models.CharField(choices=[('NP', 'Not Paid'), ('PP', 'Partially Paid'), ('FP', 'Fully Paid')], default='NP', max_length=2),
        ),
    ]
