# Generated by Django 5.1.1 on 2025-01-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0037_remove_invoice_paid_invoice_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='exit_status',
            field=models.BooleanField(default=False),
        ),
    ]
