# Generated by Django 5.1.1 on 2025-01-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0038_invoice_exit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='exit_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
