# Generated by Django 5.1.1 on 2025-01-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0039_invoice_exit_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
