# Generated by Django 5.1.1 on 2025-01-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0041_alter_invoice_is_fraud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_fraud',
        ),
    ]
