# Generated by Django 5.1.1 on 2025-01-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0042_remove_invoice_is_fraud'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
