# Generated by Django 4.2.4 on 2023-10-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "acn",
                    models.CharField(
                        max_length=50, verbose_name="Accounting Document Number"
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "total",
                    models.IntegerField(max_length=15, verbose_name="Total Amount"),
                ),
            ],
        ),
    ]
