# Generated by Django 4.2.4 on 2023-10-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0003_alter_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("AT", "Achat Tôle"),
                    ("FAA", "Frais accesoires d'achat"),
                    ("FR", "Frais Roulage"),
                    ("AM", "Achat de marchandises"),
                    ("RRROA", "RRR obtenus sur achats"),
                    ("AMET", "Achats de matériels,équipements et travaux"),
                    ("AEPS", "Achat d'études et de préstation de service"),
                    ("FPT", "Frais postaux et de télécommunications"),
                    ("PPRP", "Publicité, publication, relations publiques"),
                    ("ANSMF", "Achat non stockés de matières et fournitures"),
                    ("AEPS", "Achat d'études et de préstation de service"),
                    ("RP", "Rémunérations du personnel"),
                    ("RD", "Rémunération des dirigeants"),
                    ("RIH", "Rémunérations d'intermédiaires et honoraires"),
                    ("CBA", "Services bancaires et assimilés"),
                    ("ERM", "Entretien, réparation et maintenance"),
                    ("CD", "Cotisations et divers"),
                    ("TBCP", "Transport de biens et transport collectif du personnel"),
                    ("CI", "Charges d'intérêts"),
                    ("IT", "impôts et taxes"),
                    ("AA", "Autres approvisionnements"),
                    ("VS", "Variation des stocks"),
                    ("PCI", "Pertes sur créances irrécouvrables"),
                ],
                default="AT",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
