# Generated by Django 4.2.4 on 2023-11-04 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0006_jirama"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jirama",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
