# Generated by Django 5.1.1 on 2025-01-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_jirama_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirama',
            name='kw',
            field=models.IntegerField(null=True),
        ),
    ]
