# Generated by Django 4.2.5 on 2023-09-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_be'),
    ]

    operations = [
        migrations.AlterField(
            model_name='be',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customers'),
        ),
    ]
