# Generated by Django 4.2.5 on 2023-09-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_be_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BE',
        ),
    ]
