# Generated by Django 4.1 on 2023-10-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_address_customers_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
