# Generated by Django 4.1.7 on 2023-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customers_company_alter_customers_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='company',
            field=models.CharField(default='ok', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='location',
            field=models.CharField(default='av', max_length=100),
            preserve_default=False,
        ),
    ]
