# Generated by Django 4.2.5 on 2024-10-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_customers_t"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customers_t",
        ),
    ]
